import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/auth/',
          '/private/',
          '/_next/',
          '/dashboard/',
          '/dashboard',
          '/inventory/',
          '/inventory',
          '/orders/',
          '/orders',
          '/tracking/',
          '/tracking',
          '/warehouses/',
          '/warehouses',
          '/couriers/',
          '/couriers',
          '/courier/',
          '/courier',
          '/reports/',
          '/reports',
          '/products/',
          '/products',
          '/Stock/',
          '/Stock',
          '/pod/',
          '/pod',
          '/upload-orders/',
          '/upload-orders',
          '/customer/',
          '/customer',
          '/profile/',
          '/profile',
          '/settings/',
          '/settings',
          '/suppliers/',
          '/suppliers',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/auth/',
          '/private/',
          '/dashboard/',
          '/dashboard',
          '/inventory/',
          '/orders/',
          '/tracking/',
          '/warehouses/',
          '/couriers/',
          '/courier/',
          '/reports/',
          '/products/',
          '/Stock/',
          '/pod/',
          '/upload-orders/',
          '/customer/',
          '/profile/',
          '/settings/',
          '/suppliers/',
        ],
      },
    ],
    sitemap: 'https://omniwtms.com/sitemap.xml',
    host: 'https://omniwtms.com',
  }
}
